name: linuxptp-rt
base: core22
summary: Linux Precision Time Protocol (PTP)
description: |
  Snap packaging for linuxptp,
  an implementation of the Precision Time Protocol (PTP) according to IEEE standard 1588 for Linux.
license: GPL-2.0-only
adopt-info: linuxptp

grade: devel
confinement: strict

plugs:
  ptp-device-files:
    interface: system-files
    write:
      - /dev/ptp0
  ptp4l-runtime-files:
    interface: system-files
    write:
      - /run/ptp4l
      - /run/ptp4lro
  ptp-runtime-files:
    interface: system-files
    write:
      - /run
  ptp-etc-files:
    interface: system-files
    read:
      - /etc/linuxptp

parts:
  linuxptp:
    plugin: make
    source: git://git.code.sf.net/p/linuxptp/code
    source-tag: v4.0
    source-depth: 1
    # make-parameters: 
    override-build: |
      craftctl default

      install -DT COPYING $CRAFT_PART_INSTALL/usr/share/doc/COPYING

      craftctl set version="$(git describe --tags | sed s/v//)+snap"

apps:
  hwstamp-ctl: # renamed to bypass character restrictions
    command: usr/local/sbin/hwstamp_ctl
    plugs:
      - network-bind
      - network-control
  nsm:
    command: usr/local/sbin/nsm
    plugs:
      - network-bind
      - network-control
      - ptp
      - ptp-etc-files
  phc-ctl: # renamed to bypass character restrictions
    command: usr/local/sbin/phc_ctl
    plugs:
      - network-bind
      - network-control
      - ptp
      - ptp-device-files
      - microstack-support
      - time-control

  phc2sys:
    command: usr/local/sbin/phc2sys
    plugs:
      - network-bind
      - network-control
      - ptp
      - ptp-device-files
      - ptp-runtime-files
      - microstack-support
      - time-control

  pmc:
    command: usr/local/sbin/pmc
    plugs:
      - network-bind
      - network-control
      - ptp
      - ptp-runtime-files
  ptp4l:
    command: usr/local/sbin/ptp4l
    plugs:
      - network
      - network-bind
      - network-control
      - time-control
      - system-packages-doc
      - ptp
      - ptp-device-files
      - ptp4l-runtime-files

  timemaster:
    command: usr/local/sbin/timemaster
    plugs:
      - network-bind
      - network-control
      - ptp
      - ptp-etc-files
      - ptp-runtime-files
      
  ts2phc:
    command: usr/local/sbin/ts2phc
    plugs:
      - network-bind
      - network-control
      - ptp
      - ptp-device-files
      - microstack-support
      - time-control
  tz2alt:
    command: usr/local/sbin/tz2alt
    plugs:
      - network-bind
      - network-control
      - ptp
      - ptp-runtime-files
      - system-packages-doc
