name: linuxptp
base: core22
summary: Linux Precision Time Protocol (PTP)
description: |
  Snap packaging for linuxptp,
  an implementation of the Precision Time Protocol (PTP) according to IEEE standard 1588 for Linux.
license: GPL-2.0-only
adopt-info: linuxptp

grade: devel
confinement: devmode

parts:
  linuxptp:
    plugin: nil
    stage-packages:
      - linuxptp
    override-build: |
      craftctl default

      VERSION=$($CRAFT_PART_INSTALL/usr/sbin/ptp4l -v)
      craftctl set version=$VERSION+snap

apps:
  hwstamp-ctl: # renamed to bypass character restrictions
    command: usr/sbin/hwstamp_ctl
  nsm:
    command: usr/sbin/nsm
  phc-ctl: # renamed to bypass character restrictions
    command: usr/sbin/phc_ctl
  phc2sys:
    command: usr/sbin/phc2sys
  pmc:
    command: usr/sbin/pmc
  ptp4l:
    command: usr/sbin/ptp4l
  timemaster:
    command: usr/sbin/timemaster
  ts2phc:
    command: usr/sbin/ts2phc
  # tz2alt: # available starting from linuxptp v4.0
  #   command: usr/sbin/tz2alt
