name: linuxptp-rt
base: core22
summary: Linux Precision Time Protocol (PTP)
description: |
  Snap packaging for linuxptp,
  an implementation of the Precision Time Protocol (PTP) according to IEEE standard 1588 for Linux.
license: GPL-2.0-only
adopt-info: linuxptp

grade: devel
confinement: strict

# plugs:
#   system-dev-ptp0:
#     interface: system-files
#     write:
#       - /dev/ptp0
#   system-dev-pts:
#     interface: system-files
#     write:
#       - /dev/pts
#   system-run-ptp4l:
#     interface: system-files
#     write:
#       - /run/ptp4l
#       - /run/ptp4lro
#   # Access to the Unix Domain Socket (UDS) file 
#   # located in /run/pmc.* used by pmc application
#   system-run:
#     interface: system-files
#     write:
#       - /run

parts:
  local:
    plugin: nil
    source: snap/local
    override-build: |
      CONF=$SNAPCRAFT_PART_INSTALL/etc
      mkdir -p $CONF
      cp -v etc/* $CONF/
  
  linuxptp:
    after: [local]
    plugin: make
    source: git://git.code.sf.net/p/linuxptp/code
    source-tag: v4.0
    source-depth: 1
    # make-parameters: 
    override-build: |
      craftctl default

      DOC=$CRAFT_PART_INSTALL/usr/share/doc
      mkdir -p $DOC
      cp COPYING $DOC/

      CONF=$SNAPCRAFT_PART_INSTALL/etc
      mkdir -p $CONF
      cp -v configs/* $CONF

      # Replace /var/run with /run/snap.linuxptp-rt
      cp $CONF/default.cfg $CONF/snap.cfg
      sed -i 's/\/var\/run/\/run\/snap.linuxptp-rt/g' $CONF/snap.cfg

      echo "
      # Additional configuration for the snap
      refclock_sock_address	/run/snap.linuxptp-rt/refclock.ptp.sock
      uds_address		        /run/snap.linuxptp-rt/ptp4l
      uds_ro_address		    /run/snap.linuxptp-rt/ptp4lro
      " >> $CONF/gPTP.cfg

      craftctl set version="$(git describe --tags | sed s/v//)+snap"
      
apps:
  hwstamp-ctl: # renamed to bypass character restrictions
    command: usr/local/sbin/hwstamp_ctl
    plugs:
      - network-bind
      - network-control
  nsm:
    command: usr/local/sbin/nsm
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
  phc-ctl: # renamed to bypass character restrictions
    command: usr/local/sbin/phc_ctl
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
      # Access to system date and time
      - time-control
      # Access to system logs and data
      - system-backup
      - log-observe

  phc2sys:
    command: usr/local/sbin/phc2sys
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
      # Access to system date and time
      - time-control
      # Access to system logs and data
      - system-backup
      - log-observe

  pmc:
    command: usr/local/sbin/pmc
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
  ptp4l:
    command: usr/local/sbin/ptp4l
    plugs:
      - network
      - network-bind
      - network-control
      # Access to system date and time
      - time-control
      # Access to PTP subsystem and files
      - ptp

  timemaster:
    command: usr/local/sbin/timemaster
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
      
  ts2phc:
    command: usr/local/sbin/ts2phc
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
      # Access to system date and time
      - time-control
      # Access to read system logs and data
      - system-backup
      - log-observe
  tz2alt:
    command: usr/local/sbin/tz2alt
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
      
